export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"

export ZDOTDIR="$HOME/.config/zsh"
export PATH="$PATH:$HOME/.config/scripts"

export CARGO_HOME="$XDG_DATA_HOME/cargo"
export FASTAI_HOME="$XDG_DATA_HOME/.fastai"
export GIT_CONFIG_GLOBAL="$XDG_CONFIG_HOME/git/config"
export GOPATH="$XDG_DATA_HOME/go"
export GOBIN="$GOPATH/bin"
export GOMODCACHE="$XDG_CACHE_HOME/go/mod"
export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc-2.0"
export _JAVA_OPTIONS=-Djava.util.prefs.userRoot="$XDG_CONFIG_HOME/java"
export JUPYTER_CONFIG_DIR="$XDG_CONFIG_HOME/jupyter"
export JUPYTER_PLATFORM_DIRS="1"
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"
export PYTHON_HISTORY="$XDG_STATE_HOME/python_history"
export PYTHONPYCACHEPREFIX="$XDG_CACHE_HOME/python"
export PYTHONUSERBASE="$XDG_DATA_HOME/python"
export WINEPREFIX="$XDG_DATA_HOME/wineprefixes/default"
export KAGGLE_CONFIG_DIR="$XDG_CONFIG_HOME/kaggle"
