set -a terminal-features "screen-256color:RGB"
set -g prefix ^E
set -g base-index 1
set -g set-clipboard on
set -g status-position top
set -g status-justify absolute-centre
set -g status-style "bg=default"
set -g window-status-current-style "bold"
set -g status-left "#S"
set -g status-right ""
set -g mode-keys vi

unbind ^B 
bind r source-file ~/.config/tmux/tmux.conf
