set -g prefix ^Space
set -ag terminal-features "screen-256color:RGB"
set -g renumber-windows on
set -g base-index 1
set -g set-clipboard on
set -g mode-keys vi

set -g status-position top
set -g status-justify absolute-centre
set -g status-style "bg=default"
set -g window-status-current-style "bold"
set -g status-left "#S"
set -g status-right ""

unbind ^B 
bind r source-file ~/.config/tmux/tmux.conf

unbind '"'
bind \\ split-window -h -c "#{pane_current_path}"
unbind %
bind - split-window -v -c "#{pane_current_path}"

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind X confirm-before -p "Kill window #W? (y/n)" kill-window
bind t confirm-before -p "Kill current session (#S) and switch to another? (y/n)" "run-shell '$HOME/.config/tmux/scripts/kill-current-session.sh'"
bind T confirm-before -p "Kill all other sessions? (y/n)" "run-shell '$HOME/.config/tmux/scripts/kill-all-sessions.sh'"

bind f run-shell "$HOME/.config/tmux/scripts/manage-sessions.sh"
