# add_newline = false

format = """
$directory \
$git_branch \
$git_commit\
$git_state\
$git_metrics\
$git_status\
$fill \
$python \
$cmd_duration \
$character \
"""

[character]
format = "\n$symbol "
success_symbol = '[\$](fg:#ffffff)'
error_symbol = '[\$](fg:#ffffff)'

[directory]
style = 'fg:#ffffff'

[cmd_duration]
format = '\[[$duration]($style)\] '
style = 'fg:#ffffff'

[fill]
symbol = ' '

[python]
format = '\[[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\))]($style)\]'
style = 'fg:#ffffff'
symbol = 'Python '

[git_branch]
format = '\[[$symbol$branch(:$remote_branch)]($style)\]'
style = 'fg:#ffffff'
symbol = 'branch: '

[git_status]
style = 'fg:#ffffff'
deleted = 'x'
